WITH Transactions_Clean as (

    SELECT 
    CAST(CUSTOMER_ID AS INT) AS CUSTOMER_ID,
    PRODUCT_ID,
    CAST(PAYMENT_MONTH AS DATE) AS PAY_DATE,
    CAST(REVENUE_TYPE AS INT) AS REVENUE_TYPE,
    CAST(REVENUE AS INT) AS REVENUE,
    CAST(QUANTITY AS INT) AS QUANTITY,
    DIMENSION1,
    DIMENSION2,
    DIMENSION3,
    DIMENSION4,
    DIMENSION5,
    DIMENSION6,
    DIMENSION7,
    DIMENSION8,
    DIMENSION9,
    DIMENSION10,
    COMPANIES



    


    FROM {{ source('Portal', 'TRANSACTIONS') }}

)




SELECT DISTINCT * 
FROM Transactions_Clean
WHERE CUSTOMER_ID IS NOT NULL